### ISSUE TITLE
Issue with Dynasty toggle button on player rankings page

### ISSUE THREAD

**Issue by orrefailaT** [jmtimper/dynasty-daddy#216]
Steps to reproduce:
1. Navigate to dynasty-daddy.com/players/values

2. Press the SF toggle once. The player values update correctly, but the list is not re-sorted.

3. Subsequent presses of the SF toggle will change the sort order, but the order will be for the opposite value of the SF toggle. Player values still update correctly.

4. Modifying any other toggle or checkbox resets the players to the correct order corresponding to the SF toggle value.

**Comment by jmtimper** [comment]
Thanks for leaving the bug ticket! Issue has been resolved
