### ISSUE TITLE
Immaculate Gridiron - Kellen Winslow

### ISSUE THREAD

**Issue by sbingo** [jmtimper/dynasty-daddy#541]
I love that you're using NFL data to create a grid for football. I know data cleanup is annoying because it never ends, but I thought I'd point out something I am pretty certain is an error. The image that appears for Kellen Winslow II is Kellen Winslow I. If not for the fact that the elder Winslow is a Hall of Famer, this wouldn't be worth mentioning, as this is just one piece of data amongst millions.
Thanks for creating the grid and all your work on the site.

**Comment by jmtimper** [comment]
Thanks for the feedback! I updated the image to be the pfr image. Keep the data tweaks coming if you find more.
